### ISSUE TITLE
永远无法逃过10个限制

### ISSUE THREAD

**Issue by jakehu** [williamnie/91pron-#4]
访问地址是直接 91pron.com

**Comment by williamnie** [comment]
确实,最开始爬取的时候,并没有,但是后来我一下子爬取的太多了,可能被网址检测到了,现在他们升级了,分析网页发现,和原来的实现方式不一样了,现在要想破解10个的限制,只能给代码挂代理,写过一个demo,但是可用代理很少,就没在研究它

**Comment by jakehu** [comment]
其实不用代理，利用爬虫，随机IP就行了

**Comment by fuckex** [comment]
最简单的跑备用站，我的有代码，可以直接用，大概一天一夜可以全站爬完

**Comment by williamnie** [comment]
你的意思是如果一个网址遇到限制了,马上切换到91其他的备用网站么

**Comment by williamnie** [comment]
already fix 10 limit
